tasks:
  - name: Install required dependencies for cypress
    command: |
      apt-get install xvfb
  - name: Upgrade npm and pnpm
    command: |
      npm i -g npm;
      npm i -g pnpm;
      echo "Upgrade completed. Exiting...";
      sleep 10;
      exit;
