tasks:
  - name: Upgrade npm and pnpm
    command: |
      npm i -g npm;
      npm i -g pnpm;
      echo "Upgrade completed. Exiting...";
      sleep 3;
      exit;
  - name: Install dependencies
    command: pnpm i --frozen-lockfile;
