name: Release

on:
  workflow_run:
    workflows: ["Deployment"]
    branches: [main]
    types:
      - completed

jobs:
  release-please:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release

      - uses: ./.github/workflows/node-setup.yml
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - name: Build packages
        run: pnpm build
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

      - name: Publish packages
        run: pnpm -r publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}

  error:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deployment did not run successfully"
      - run: exit 1
